name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}


      - name: Print env
        run: |
          echo ${{ github.ref_name }}

      - name: Add execution permissions to mvnw
        run: chmod +x mvnw

      - name: Set Release Version
        run: |
          echo "Setting the release version to ${{ github.ref_name }}"
          ./mvnw versions:set -DnewVersion="${{ github.ref_name }}"
          ./mvnw versions:commit

      - name: Build component
        run: ./mvnw install -Pdirectory

      - name: Deploy to GitHub releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: target/minicalendar-${{ github.ref_name }}.jar
          asset_name: minicalendar-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive
          upload_url: ${{ steps.get_release.outputs.upload_url }}
