name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add execution permissions to mvnw
        run: chmod +x mvnw

      - name: Set Release Version
        run: |
          ./mvnw versions:set -DnewVersion="$GITHUB_REF | awk -F/ '{print $NF}'"
          ./mvnw versions:commit

      - name: Build component
        run: ./mvnw install -Pdirectory

      - name: Deploy to GitHub releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/minicalendar-$TAG.jar
          asset_name: minicalendar-$TAG.jar
          asset_content_type: application/java-archive
