name: Deploy to Railway

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Release ]
    types:
      - completed

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log Ref Data
        run: echo "Deploying to Railway.app using image tag ${{ github.ref_name }}"

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy to Railway
        run: |
            railway variables set IMAGE_TAG ${{ github.ref_name }}
            railway variables set RAILWAY_DOCKERFILE_PATH  ./showcase/Dockerfile.Railway
            railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
