name: Deploy to Railway

on: 
  workflow_dispatch:
  workflow_run:
    workflows: [ Release ]
    types:
      - completed

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Prepare Environment
        run: chmod +x mvnw

      - name: Build Reactor
        run: ./mvnw --batch-mode -pl '!addon,!showcase' install

      - name: Build Add-on
        run: ./mvnw --batch-mode -Pdirectory -pl :addon install

      - name: Build Showcase
        run: ./mvnw --batch-mode -Pproduction -pl :showcase install

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy to Railway
        run: cd showcase && railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
