name: Build and Release

on:
  release:
    types: [published]

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Environment
        run: chmod +x mvnw

      - name: Set Release Version
        run: |
          ./mvnw versions:set -DnewVersion="${{ github.ref_name }}"
          ./mvnw versions:commit

      - name: Build component
        run: ./mvnw install -Pdirectory

      - name: Deploy to GitHub releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: target/minicalendar-${{ github.ref_name }}.zip
          asset_name: minicalendar-${{ github.ref_name }}.zip
          asset_content_type: application/zip
          upload_url: ${{ github.event.release.upload_url }}
